// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CRPScircRcpp
arma::vec CRPScircRcpp(arma::vec Obs_r, arma::mat Sim_r);
RcppExport SEXP _CircSpaceTime_CRPScircRcpp(SEXP Obs_rSEXP, SEXP Sim_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Obs_r(Obs_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sim_r(Sim_rSEXP);
    rcpp_result_gen = Rcpp::wrap(CRPScircRcpp(Obs_r, Sim_r));
    return rcpp_result_gen;
END_RCPP
}
// ProjKrigSpCpp
List ProjKrigSpCpp(arma::vec sigma2, arma::vec rho, arma::vec tau, arma::mat alpha, arma::mat r, int n, int nsample, arma::mat H_tot, int nprev, NumericVector x, String corr_fun, double kappa_matern);
RcppExport SEXP _CircSpaceTime_ProjKrigSpCpp(SEXP sigma2SEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP alphaSEXP, SEXP rSEXP, SEXP nSEXP, SEXP nsampleSEXP, SEXP H_totSEXP, SEXP nprevSEXP, SEXP xSEXP, SEXP corr_funSEXP, SEXP kappa_maternSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H_tot(H_totSEXP);
    Rcpp::traits::input_parameter< int >::type nprev(nprevSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type corr_fun(corr_funSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_matern(kappa_maternSEXP);
    rcpp_result_gen = Rcpp::wrap(ProjKrigSpCpp(sigma2, rho, tau, alpha, r, n, nsample, H_tot, nprev, x, corr_fun, kappa_matern));
    return rcpp_result_gen;
END_RCPP
}
// ProjKrigSpTiCpp
List ProjKrigSpTiCpp(arma::vec sigma2, arma::vec rho_sp, arma::vec tau, arma::mat alpha, arma::mat r, int n, int nsample, arma::mat H_tot, arma::mat Ht_tot, int nprev, NumericVector x, arma::vec rho_t, arma::vec sep_par);
RcppExport SEXP _CircSpaceTime_ProjKrigSpTiCpp(SEXP sigma2SEXP, SEXP rho_spSEXP, SEXP tauSEXP, SEXP alphaSEXP, SEXP rSEXP, SEXP nSEXP, SEXP nsampleSEXP, SEXP H_totSEXP, SEXP Ht_totSEXP, SEXP nprevSEXP, SEXP xSEXP, SEXP rho_tSEXP, SEXP sep_parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho_sp(rho_spSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H_tot(H_totSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ht_tot(Ht_totSEXP);
    Rcpp::traits::input_parameter< int >::type nprev(nprevSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho_t(rho_tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sep_par(sep_parSEXP);
    rcpp_result_gen = Rcpp::wrap(ProjKrigSpTiCpp(sigma2, rho_sp, tau, alpha, r, n, nsample, H_tot, Ht_tot, nprev, x, rho_t, sep_par));
    return rcpp_result_gen;
END_RCPP
}
// ProjSpRcpp
List ProjSpRcpp(int ad_start, int ad_end, double ad_exp, int burnin, int thin, int nSamples_save, int n_j, int iter_z, NumericVector prior_tau, NumericVector prior_sigma2, NumericVector prior_rho, arma::mat prior_alpha_sigma, arma::vec prior_alpha_mu, double sdtau, double sdsigma2, double sdrho, arma::vec sdr, double tau, double sigma2, double rho, arma::vec alpha, NumericVector r, NumericVector x, arma::mat H, double acceptratio, String corr_fun, double kappa_matern);
RcppExport SEXP _CircSpaceTime_ProjSpRcpp(SEXP ad_startSEXP, SEXP ad_endSEXP, SEXP ad_expSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP nSamples_saveSEXP, SEXP n_jSEXP, SEXP iter_zSEXP, SEXP prior_tauSEXP, SEXP prior_sigma2SEXP, SEXP prior_rhoSEXP, SEXP prior_alpha_sigmaSEXP, SEXP prior_alpha_muSEXP, SEXP sdtauSEXP, SEXP sdsigma2SEXP, SEXP sdrhoSEXP, SEXP sdrSEXP, SEXP tauSEXP, SEXP sigma2SEXP, SEXP rhoSEXP, SEXP alphaSEXP, SEXP rSEXP, SEXP xSEXP, SEXP HSEXP, SEXP acceptratioSEXP, SEXP corr_funSEXP, SEXP kappa_maternSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ad_start(ad_startSEXP);
    Rcpp::traits::input_parameter< int >::type ad_end(ad_endSEXP);
    Rcpp::traits::input_parameter< double >::type ad_exp(ad_expSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type nSamples_save(nSamples_saveSEXP);
    Rcpp::traits::input_parameter< int >::type n_j(n_jSEXP);
    Rcpp::traits::input_parameter< int >::type iter_z(iter_zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau(prior_tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_sigma2(prior_sigma2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_rho(prior_rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prior_alpha_sigma(prior_alpha_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_alpha_mu(prior_alpha_muSEXP);
    Rcpp::traits::input_parameter< double >::type sdtau(sdtauSEXP);
    Rcpp::traits::input_parameter< double >::type sdsigma2(sdsigma2SEXP);
    Rcpp::traits::input_parameter< double >::type sdrho(sdrhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sdr(sdrSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type acceptratio(acceptratioSEXP);
    Rcpp::traits::input_parameter< String >::type corr_fun(corr_funSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_matern(kappa_maternSEXP);
    rcpp_result_gen = Rcpp::wrap(ProjSpRcpp(ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, iter_z, prior_tau, prior_sigma2, prior_rho, prior_alpha_sigma, prior_alpha_mu, sdtau, sdsigma2, sdrho, sdr, tau, sigma2, rho, alpha, r, x, H, acceptratio, corr_fun, kappa_matern));
    return rcpp_result_gen;
END_RCPP
}
// ProjSpTiRcpp
List ProjSpTiRcpp(int ad_start, int ad_end, double ad_exp, int burnin, int thin, int nSamples_save, int n_j, int iter_z, NumericVector prior_tau, NumericVector prior_sigma2, NumericVector prior_rho_sp, arma::mat prior_alpha_sigma, arma::vec prior_alpha_mu, NumericVector prior_rho_t, NumericVector prior_sep_par, double sdtau, double sdsigma2, double sdrho_sp, arma::vec sdr, double sdrho_t, double sdsep_par, double tau, double sigma2, double rho_sp, arma::vec alpha, NumericVector r, double rho_t, double sep_par, NumericVector x, arma::mat H, arma::mat Ht, double acceptratio);
RcppExport SEXP _CircSpaceTime_ProjSpTiRcpp(SEXP ad_startSEXP, SEXP ad_endSEXP, SEXP ad_expSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP nSamples_saveSEXP, SEXP n_jSEXP, SEXP iter_zSEXP, SEXP prior_tauSEXP, SEXP prior_sigma2SEXP, SEXP prior_rho_spSEXP, SEXP prior_alpha_sigmaSEXP, SEXP prior_alpha_muSEXP, SEXP prior_rho_tSEXP, SEXP prior_sep_parSEXP, SEXP sdtauSEXP, SEXP sdsigma2SEXP, SEXP sdrho_spSEXP, SEXP sdrSEXP, SEXP sdrho_tSEXP, SEXP sdsep_parSEXP, SEXP tauSEXP, SEXP sigma2SEXP, SEXP rho_spSEXP, SEXP alphaSEXP, SEXP rSEXP, SEXP rho_tSEXP, SEXP sep_parSEXP, SEXP xSEXP, SEXP HSEXP, SEXP HtSEXP, SEXP acceptratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ad_start(ad_startSEXP);
    Rcpp::traits::input_parameter< int >::type ad_end(ad_endSEXP);
    Rcpp::traits::input_parameter< double >::type ad_exp(ad_expSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type nSamples_save(nSamples_saveSEXP);
    Rcpp::traits::input_parameter< int >::type n_j(n_jSEXP);
    Rcpp::traits::input_parameter< int >::type iter_z(iter_zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau(prior_tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_sigma2(prior_sigma2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_rho_sp(prior_rho_spSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prior_alpha_sigma(prior_alpha_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_alpha_mu(prior_alpha_muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_rho_t(prior_rho_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_sep_par(prior_sep_parSEXP);
    Rcpp::traits::input_parameter< double >::type sdtau(sdtauSEXP);
    Rcpp::traits::input_parameter< double >::type sdsigma2(sdsigma2SEXP);
    Rcpp::traits::input_parameter< double >::type sdrho_sp(sdrho_spSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sdr(sdrSEXP);
    Rcpp::traits::input_parameter< double >::type sdrho_t(sdrho_tSEXP);
    Rcpp::traits::input_parameter< double >::type sdsep_par(sdsep_parSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type rho_sp(rho_spSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type rho_t(rho_tSEXP);
    Rcpp::traits::input_parameter< double >::type sep_par(sep_parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ht(HtSEXP);
    Rcpp::traits::input_parameter< double >::type acceptratio(acceptratioSEXP);
    rcpp_result_gen = Rcpp::wrap(ProjSpTiRcpp(ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, iter_z, prior_tau, prior_sigma2, prior_rho_sp, prior_alpha_sigma, prior_alpha_mu, prior_rho_t, prior_sep_par, sdtau, sdsigma2, sdrho_sp, sdr, sdrho_t, sdsep_par, tau, sigma2, rho_sp, alpha, r, rho_t, sep_par, x, H, Ht, acceptratio));
    return rcpp_result_gen;
END_RCPP
}
// WrapKrigSpCpp
List WrapKrigSpCpp(NumericVector sigma2, NumericVector alpha, NumericVector rho, IntegerMatrix k, int n, int nsample, arma::mat H_tot, int nprev, NumericVector x, String corr_fun, double kappa_matern);
RcppExport SEXP _CircSpaceTime_WrapKrigSpCpp(SEXP sigma2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP kSEXP, SEXP nSEXP, SEXP nsampleSEXP, SEXP H_totSEXP, SEXP nprevSEXP, SEXP xSEXP, SEXP corr_funSEXP, SEXP kappa_maternSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H_tot(H_totSEXP);
    Rcpp::traits::input_parameter< int >::type nprev(nprevSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type corr_fun(corr_funSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_matern(kappa_maternSEXP);
    rcpp_result_gen = Rcpp::wrap(WrapKrigSpCpp(sigma2, alpha, rho, k, n, nsample, H_tot, nprev, x, corr_fun, kappa_matern));
    return rcpp_result_gen;
END_RCPP
}
// WrapKrigSpTiCpp
List WrapKrigSpTiCpp(NumericVector sigma2, NumericVector alpha, NumericVector rho_sp, NumericVector rho_t, NumericVector sep_par, IntegerMatrix k, int n, int nsample, arma::mat H_tot, arma::mat Ht_tot, int nprev, NumericVector x);
RcppExport SEXP _CircSpaceTime_WrapKrigSpTiCpp(SEXP sigma2SEXP, SEXP alphaSEXP, SEXP rho_spSEXP, SEXP rho_tSEXP, SEXP sep_parSEXP, SEXP kSEXP, SEXP nSEXP, SEXP nsampleSEXP, SEXP H_totSEXP, SEXP Ht_totSEXP, SEXP nprevSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho_sp(rho_spSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho_t(rho_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sep_par(sep_parSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H_tot(H_totSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ht_tot(Ht_totSEXP);
    Rcpp::traits::input_parameter< int >::type nprev(nprevSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(WrapKrigSpTiCpp(sigma2, alpha, rho_sp, rho_t, sep_par, k, n, nsample, H_tot, Ht_tot, nprev, x));
    return rcpp_result_gen;
END_RCPP
}
// WrapSpRcpp
List WrapSpRcpp(int ad_start, int ad_end, double ad_exp, int burnin, int thin, int nSamples_save, int n_j, NumericVector prior_alpha, NumericVector prior_rho, NumericVector prior_sigma2, double sdrho, double sdsigma2, double alpha, double rho, double sigma2, IntegerVector k, NumericVector x, arma::mat H, double acceptratio, String corr_fun, double kappa_matern);
RcppExport SEXP _CircSpaceTime_WrapSpRcpp(SEXP ad_startSEXP, SEXP ad_endSEXP, SEXP ad_expSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP nSamples_saveSEXP, SEXP n_jSEXP, SEXP prior_alphaSEXP, SEXP prior_rhoSEXP, SEXP prior_sigma2SEXP, SEXP sdrhoSEXP, SEXP sdsigma2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP sigma2SEXP, SEXP kSEXP, SEXP xSEXP, SEXP HSEXP, SEXP acceptratioSEXP, SEXP corr_funSEXP, SEXP kappa_maternSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ad_start(ad_startSEXP);
    Rcpp::traits::input_parameter< int >::type ad_end(ad_endSEXP);
    Rcpp::traits::input_parameter< double >::type ad_exp(ad_expSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type nSamples_save(nSamples_saveSEXP);
    Rcpp::traits::input_parameter< int >::type n_j(n_jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_alpha(prior_alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_rho(prior_rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_sigma2(prior_sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type sdrho(sdrhoSEXP);
    Rcpp::traits::input_parameter< double >::type sdsigma2(sdsigma2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type acceptratio(acceptratioSEXP);
    Rcpp::traits::input_parameter< String >::type corr_fun(corr_funSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_matern(kappa_maternSEXP);
    rcpp_result_gen = Rcpp::wrap(WrapSpRcpp(ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, prior_alpha, prior_rho, prior_sigma2, sdrho, sdsigma2, alpha, rho, sigma2, k, x, H, acceptratio, corr_fun, kappa_matern));
    return rcpp_result_gen;
END_RCPP
}
// WrapSpTiRcpp
List WrapSpTiRcpp(int ad_start, int ad_end, double ad_exp, int burnin, int thin, int nSamples_save, int n_j, NumericVector prior_alpha, NumericVector prior_rho_sp, NumericVector prior_rho_t, NumericVector prior_sep_par, NumericVector prior_sigma2, double sdrho_sp, double sdrho_t, double sdsep_par, double sdsigma2, double alpha, double rho_sp, double rho_t, double sep_par, double sigma2, IntegerVector k, NumericVector x, arma::mat H, arma::mat Ht, double acceptratio);
RcppExport SEXP _CircSpaceTime_WrapSpTiRcpp(SEXP ad_startSEXP, SEXP ad_endSEXP, SEXP ad_expSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP nSamples_saveSEXP, SEXP n_jSEXP, SEXP prior_alphaSEXP, SEXP prior_rho_spSEXP, SEXP prior_rho_tSEXP, SEXP prior_sep_parSEXP, SEXP prior_sigma2SEXP, SEXP sdrho_spSEXP, SEXP sdrho_tSEXP, SEXP sdsep_parSEXP, SEXP sdsigma2SEXP, SEXP alphaSEXP, SEXP rho_spSEXP, SEXP rho_tSEXP, SEXP sep_parSEXP, SEXP sigma2SEXP, SEXP kSEXP, SEXP xSEXP, SEXP HSEXP, SEXP HtSEXP, SEXP acceptratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ad_start(ad_startSEXP);
    Rcpp::traits::input_parameter< int >::type ad_end(ad_endSEXP);
    Rcpp::traits::input_parameter< double >::type ad_exp(ad_expSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type nSamples_save(nSamples_saveSEXP);
    Rcpp::traits::input_parameter< int >::type n_j(n_jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_alpha(prior_alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_rho_sp(prior_rho_spSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_rho_t(prior_rho_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_sep_par(prior_sep_parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_sigma2(prior_sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type sdrho_sp(sdrho_spSEXP);
    Rcpp::traits::input_parameter< double >::type sdrho_t(sdrho_tSEXP);
    Rcpp::traits::input_parameter< double >::type sdsep_par(sdsep_parSEXP);
    Rcpp::traits::input_parameter< double >::type sdsigma2(sdsigma2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho_sp(rho_spSEXP);
    Rcpp::traits::input_parameter< double >::type rho_t(rho_tSEXP);
    Rcpp::traits::input_parameter< double >::type sep_par(sep_parSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ht(HtSEXP);
    Rcpp::traits::input_parameter< double >::type acceptratio(acceptratioSEXP);
    rcpp_result_gen = Rcpp::wrap(WrapSpTiRcpp(ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, prior_alpha, prior_rho_sp, prior_rho_t, prior_sep_par, prior_sigma2, sdrho_sp, sdrho_t, sdsep_par, sdsigma2, alpha, rho_sp, rho_t, sep_par, sigma2, k, x, H, Ht, acceptratio));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CircSpaceTime_CRPScircRcpp", (DL_FUNC) &_CircSpaceTime_CRPScircRcpp, 2},
    {"_CircSpaceTime_ProjKrigSpCpp", (DL_FUNC) &_CircSpaceTime_ProjKrigSpCpp, 12},
    {"_CircSpaceTime_ProjKrigSpTiCpp", (DL_FUNC) &_CircSpaceTime_ProjKrigSpTiCpp, 13},
    {"_CircSpaceTime_ProjSpRcpp", (DL_FUNC) &_CircSpaceTime_ProjSpRcpp, 27},
    {"_CircSpaceTime_ProjSpTiRcpp", (DL_FUNC) &_CircSpaceTime_ProjSpTiRcpp, 32},
    {"_CircSpaceTime_WrapKrigSpCpp", (DL_FUNC) &_CircSpaceTime_WrapKrigSpCpp, 11},
    {"_CircSpaceTime_WrapKrigSpTiCpp", (DL_FUNC) &_CircSpaceTime_WrapKrigSpTiCpp, 12},
    {"_CircSpaceTime_WrapSpRcpp", (DL_FUNC) &_CircSpaceTime_WrapSpRcpp, 21},
    {"_CircSpaceTime_WrapSpTiRcpp", (DL_FUNC) &_CircSpaceTime_WrapSpTiRcpp, 26},
    {NULL, NULL, 0}
};

RcppExport void R_init_CircSpaceTime(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
