# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CRPScircRcpp <- function(Obs_r, Sim_r) {
    .Call('_CircSpaceTime_CRPScircRcpp', PACKAGE = 'CircSpaceTime', Obs_r, Sim_r)
}

ProjKrigSpCpp <- function(sigma2, rho, tau, alpha, r, n, nsample, H_tot, nprev, x, corr_fun, kappa_matern) {
    .Call('_CircSpaceTime_ProjKrigSpCpp', PACKAGE = 'CircSpaceTime', sigma2, rho, tau, alpha, r, n, nsample, H_tot, nprev, x, corr_fun, kappa_matern)
}

ProjKrigSpTiCpp <- function(sigma2, rho_sp, tau, alpha, r, n, nsample, H_tot, Ht_tot, nprev, x, rho_t, sep_par) {
    .Call('_CircSpaceTime_ProjKrigSpTiCpp', PACKAGE = 'CircSpaceTime', sigma2, rho_sp, tau, alpha, r, n, nsample, H_tot, Ht_tot, nprev, x, rho_t, sep_par)
}

ProjSpRcpp <- function(ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, iter_z, prior_tau, prior_sigma2, prior_rho, prior_alpha_sigma, prior_alpha_mu, sdtau, sdsigma2, sdrho, sdr, tau, sigma2, rho, alpha, r, x, H, acceptratio, corr_fun, kappa_matern) {
    .Call('_CircSpaceTime_ProjSpRcpp', PACKAGE = 'CircSpaceTime', ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, iter_z, prior_tau, prior_sigma2, prior_rho, prior_alpha_sigma, prior_alpha_mu, sdtau, sdsigma2, sdrho, sdr, tau, sigma2, rho, alpha, r, x, H, acceptratio, corr_fun, kappa_matern)
}

ProjSpTiRcpp <- function(ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, iter_z, prior_tau, prior_sigma2, prior_rho_sp, prior_alpha_sigma, prior_alpha_mu, prior_rho_t, prior_sep_par, sdtau, sdsigma2, sdrho_sp, sdr, sdrho_t, sdsep_par, tau, sigma2, rho_sp, alpha, r, rho_t, sep_par, x, H, Ht, acceptratio) {
    .Call('_CircSpaceTime_ProjSpTiRcpp', PACKAGE = 'CircSpaceTime', ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, iter_z, prior_tau, prior_sigma2, prior_rho_sp, prior_alpha_sigma, prior_alpha_mu, prior_rho_t, prior_sep_par, sdtau, sdsigma2, sdrho_sp, sdr, sdrho_t, sdsep_par, tau, sigma2, rho_sp, alpha, r, rho_t, sep_par, x, H, Ht, acceptratio)
}

WrapKrigSpCpp <- function(sigma2, alpha, rho, k, n, nsample, H_tot, nprev, x, corr_fun, kappa_matern) {
    .Call('_CircSpaceTime_WrapKrigSpCpp', PACKAGE = 'CircSpaceTime', sigma2, alpha, rho, k, n, nsample, H_tot, nprev, x, corr_fun, kappa_matern)
}

WrapKrigSpTiCpp <- function(sigma2, alpha, rho_sp, rho_t, sep_par, k, n, nsample, H_tot, Ht_tot, nprev, x) {
    .Call('_CircSpaceTime_WrapKrigSpTiCpp', PACKAGE = 'CircSpaceTime', sigma2, alpha, rho_sp, rho_t, sep_par, k, n, nsample, H_tot, Ht_tot, nprev, x)
}

WrapSpRcpp <- function(ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, prior_alpha, prior_rho, prior_sigma2, sdrho, sdsigma2, alpha, rho, sigma2, k, x, H, acceptratio, corr_fun, kappa_matern) {
    .Call('_CircSpaceTime_WrapSpRcpp', PACKAGE = 'CircSpaceTime', ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, prior_alpha, prior_rho, prior_sigma2, sdrho, sdsigma2, alpha, rho, sigma2, k, x, H, acceptratio, corr_fun, kappa_matern)
}

WrapSpTiRcpp <- function(ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, prior_alpha, prior_rho_sp, prior_rho_t, prior_sep_par, prior_sigma2, sdrho_sp, sdrho_t, sdsep_par, sdsigma2, alpha, rho_sp, rho_t, sep_par, sigma2, k, x, H, Ht, acceptratio) {
    .Call('_CircSpaceTime_WrapSpTiRcpp', PACKAGE = 'CircSpaceTime', ad_start, ad_end, ad_exp, burnin, thin, nSamples_save, n_j, prior_alpha, prior_rho_sp, prior_rho_t, prior_sep_par, prior_sigma2, sdrho_sp, sdrho_t, sdsep_par, sdsigma2, alpha, rho_sp, rho_t, sep_par, sigma2, k, x, H, Ht, acceptratio)
}

